#!/bin/bash
#npm run build || exit 1

echo "[Docker] Cleaning up containers..."
#docker rm -f casino_api pg_db mongo_db frontend_frontend_1 2>/dev/null || true

#docker-compose down
#docker-compose build --no-cache
#docker-compose up -d
docker rm -f casino_api
docker-compose up -d --build
