-- =====================================================
-- COMPLETE MOBILE PREFIXES - ALL COUNTRIES
-- =====================================================
-- This migration inserts all international mobile prefixes
-- Total: 250+ countries and territories

INSERT INTO mobile_prefixes (country_code, prefix, country_name, carrier, is_active) VALUES
-- EUROPE
('AL', '+355', 'Albania', 'Various', TRUE),
('AD', '+376', 'Andorra', 'Various', TRUE),
('AT', '+43', 'Austria', 'Various', TRUE),
('BY', '+375', 'Belarus', 'Various', TRUE),
('BE', '+32', 'Belgium', 'Various', TRUE),
('BA', '+387', 'Bosnia and Herzegovina', 'Various', TRUE),
('BG', '+359', 'Bulgaria', 'Various', TRUE),
('HR', '+385', 'Croatia', 'Various', TRUE),
('CY', '+357', 'Cyprus', 'Various', TRUE),
('CZ', '+420', 'Czech Republic', 'Various', TRUE),
('DK', '+45', 'Denmark', 'Various', TRUE),
('EE', '+372', 'Estonia', 'Various', TRUE),
('FI', '+358', 'Finland', 'Various', TRUE),
('FR', '+33', 'France', 'Various', TRUE),
('DE', '+49', 'Germany', 'Various', TRUE),
('GR', '+30', 'Greece', 'Various', TRUE),
('HU', '+36', 'Hungary', 'Various', TRUE),
('IS', '+354', 'Iceland', 'Various', TRUE),
('IE', '+353', 'Ireland', 'Various', TRUE),
('IT', '+39', 'Italy', 'Various', TRUE),
('XK', '+383', 'Kosovo', 'Various', TRUE),
('LV', '+371', 'Latvia', 'Various', TRUE),
('LI', '+423', 'Liechtenstein', 'Various', TRUE),
('LT', '+370', 'Lithuania', 'Various', TRUE),
('LU', '+352', 'Luxembourg', 'Various', TRUE),
('MK', '+389', 'North Macedonia', 'Various', TRUE),
('MT', '+356', 'Malta', 'Various', TRUE),
('MD', '+373', 'Moldova', 'Various', TRUE),
('MC', '+377', 'Monaco', 'Various', TRUE),
('ME', '+382', 'Montenegro', 'Various', TRUE),
('NL', '+31', 'Netherlands', 'Various', TRUE),
('NO', '+47', 'Norway', 'Various', TRUE),
('PL', '+48', 'Poland', 'Various', TRUE),
('PT', '+351', 'Portugal', 'Various', TRUE),
('RO', '+40', 'Romania', 'Various', TRUE),
('RU', '+7', 'Russia', 'Various', TRUE),
('SM', '+378', 'San Marino', 'Various', TRUE),
('RS', '+381', 'Serbia', 'Various', TRUE),
('SK', '+421', 'Slovakia', 'Various', TRUE),
('SI', '+386', 'Slovenia', 'Various', TRUE),
('ES', '+34', 'Spain', 'Various', TRUE),
('SE', '+46', 'Sweden', 'Various', TRUE),
('CH', '+41', 'Switzerland', 'Various', TRUE),
('TR', '+90', 'Turkey', 'Various', TRUE),
('UA', '+380', 'Ukraine', 'Various', TRUE),
('GB', '+44', 'United Kingdom', 'Various', TRUE),
('VA', '+379', 'Vatican City', 'Various', TRUE),

-- NORTH AMERICA
('US', '+1', 'United States', 'Various', TRUE),
('CA', '+1', 'Canada', 'Various', TRUE),
('MX', '+52', 'Mexico', 'Various', TRUE),
('BZ', '+501', 'Belize', 'Various', TRUE),
('CR', '+506', 'Costa Rica', 'Various', TRUE),
('SV', '+503', 'El Salvador', 'Various', TRUE),
('GT', '+502', 'Guatemala', 'Various', TRUE),
('HN', '+504', 'Honduras', 'Various', TRUE),
('NI', '+505', 'Nicaragua', 'Various', TRUE),
('PA', '+507', 'Panama', 'Various', TRUE),

-- CARIBBEAN
('AG', '+1268', 'Antigua and Barbuda', 'Various', TRUE),
('BS', '+1242', 'Bahamas', 'Various', TRUE),
('BB', '+1246', 'Barbados', 'Various', TRUE),
('CU', '+53', 'Cuba', 'Various', TRUE),
('DM', '+1767', 'Dominica', 'Various', TRUE),
('DO', '+1809', 'Dominican Republic', 'Various', TRUE),
('GD', '+1473', 'Grenada', 'Various', TRUE),
('HT', '+509', 'Haiti', 'Various', TRUE),
('JM', '+1876', 'Jamaica', 'Various', TRUE),
('KN', '+1869', 'Saint Kitts and Nevis', 'Various', TRUE),
('LC', '+1758', 'Saint Lucia', 'Various', TRUE),
('VC', '+1784', 'Saint Vincent and the Grenadines', 'Various', TRUE),
('TT', '+1868', 'Trinidad and Tobago', 'Various', TRUE),

-- SOUTH AMERICA
('AR', '+54', 'Argentina', 'Various', TRUE),
('BO', '+591', 'Bolivia', 'Various', TRUE),
('BR', '+55', 'Brazil', 'Various', TRUE),
('CL', '+56', 'Chile', 'Various', TRUE),
('CO', '+57', 'Colombia', 'Various', TRUE),
('EC', '+593', 'Ecuador', 'Various', TRUE),
('GY', '+592', 'Guyana', 'Various', TRUE),
('PY', '+595', 'Paraguay', 'Various', TRUE),
('PE', '+51', 'Peru', 'Various', TRUE),
('SR', '+597', 'Suriname', 'Various', TRUE),
('UY', '+598', 'Uruguay', 'Various', TRUE),
('VE', '+58', 'Venezuela', 'Various', TRUE),

-- ASIA
('AF', '+93', 'Afghanistan', 'Various', TRUE),
('AM', '+374', 'Armenia', 'Various', TRUE),
('AZ', '+994', 'Azerbaijan', 'Various', TRUE),
('BH', '+973', 'Bahrain', 'Various', TRUE),
('BD', '+880', 'Bangladesh', 'Various', TRUE),
('BT', '+975', 'Bhutan', 'Various', TRUE),
('BN', '+673', 'Brunei', 'Various', TRUE),
('KH', '+855', 'Cambodia', 'Various', TRUE),
('CN', '+86', 'China', 'Various', TRUE),
('GE', '+995', 'Georgia', 'Various', TRUE),
('HK', '+852', 'Hong Kong', 'Various', TRUE),
('IN', '+91', 'India', 'Various', TRUE),
('ID', '+62', 'Indonesia', 'Various', TRUE),
('IR', '+98', 'Iran', 'Various', TRUE),
('IQ', '+964', 'Iraq', 'Various', TRUE),
('IL', '+972', 'Israel', 'Various', TRUE),
('JP', '+81', 'Japan', 'Various', TRUE),
('JO', '+962', 'Jordan', 'Various', TRUE),
('KZ', '+7', 'Kazakhstan', 'Various', TRUE),
('KW', '+965', 'Kuwait', 'Various', TRUE),
('KG', '+996', 'Kyrgyzstan', 'Various', TRUE),
('LA', '+856', 'Laos', 'Various', TRUE),
('LB', '+961', 'Lebanon', 'Various', TRUE),
('MO', '+853', 'Macau', 'Various', TRUE),
('MY', '+60', 'Malaysia', 'Various', TRUE),
('MV', '+960', 'Maldives', 'Various', TRUE),
('MN', '+976', 'Mongolia', 'Various', TRUE),
('MM', '+95', 'Myanmar', 'Various', TRUE),
('NP', '+977', 'Nepal', 'Various', TRUE),
('KP', '+850', 'North Korea', 'Various', TRUE),
('OM', '+968', 'Oman', 'Various', TRUE),
('PK', '+92', 'Pakistan', 'Various', TRUE),
('PS', '+970', 'Palestine', 'Various', TRUE),
('PH', '+63', 'Philippines', 'Various', TRUE),
('QA', '+974', 'Qatar', 'Various', TRUE),
('SA', '+966', 'Saudi Arabia', 'Various', TRUE),
('SG', '+65', 'Singapore', 'Various', TRUE),
('KR', '+82', 'South Korea', 'Various', TRUE),
('LK', '+94', 'Sri Lanka', 'Various', TRUE),
('SY', '+963', 'Syria', 'Various', TRUE),
('TW', '+886', 'Taiwan', 'Various', TRUE),
('TJ', '+992', 'Tajikistan', 'Various', TRUE),
('TH', '+66', 'Thailand', 'Various', TRUE),
('TL', '+670', 'Timor-Leste', 'Various', TRUE),
('TM', '+993', 'Turkmenistan', 'Various', TRUE),
('AE', '+971', 'United Arab Emirates', 'Various', TRUE),
('UZ', '+998', 'Uzbekistan', 'Various', TRUE),
('VN', '+84', 'Vietnam', 'Various', TRUE),
('YE', '+967', 'Yemen', 'Various', TRUE),

-- AFRICA
('DZ', '+213', 'Algeria', 'Various', TRUE),
('AO', '+244', 'Angola', 'Various', TRUE),
('BJ', '+229', 'Benin', 'Various', TRUE),
('BW', '+267', 'Botswana', 'Various', TRUE),
('BF', '+226', 'Burkina Faso', 'Various', TRUE),
('BI', '+257', 'Burundi', 'Various', TRUE),
('CM', '+237', 'Cameroon', 'Various', TRUE),
('CV', '+238', 'Cape Verde', 'Various', TRUE),
('CF', '+236', 'Central African Republic', 'Various', TRUE),
('TD', '+235', 'Chad', 'Various', TRUE),
('KM', '+269', 'Comoros', 'Various', TRUE),
('CG', '+242', 'Congo', 'Various', TRUE),
('CD', '+243', 'DR Congo', 'Various', TRUE),
('CI', '+225', 'Côte d''Ivoire', 'Various', TRUE),
('DJ', '+253', 'Djibouti', 'Various', TRUE),
('EG', '+20', 'Egypt', 'Various', TRUE),
('GQ', '+240', 'Equatorial Guinea', 'Various', TRUE),
('ER', '+291', 'Eritrea', 'Various', TRUE),
('ET', '+251', 'Ethiopia', 'Various', TRUE),
('GA', '+241', 'Gabon', 'Various', TRUE),
('GM', '+220', 'Gambia', 'Various', TRUE),
('GH', '+233', 'Ghana', 'Various', TRUE),
('GN', '+224', 'Guinea', 'Various', TRUE),
('GW', '+245', 'Guinea-Bissau', 'Various', TRUE),
('KE', '+254', 'Kenya', 'Various', TRUE),
('LS', '+266', 'Lesotho', 'Various', TRUE),
('LR', '+231', 'Liberia', 'Various', TRUE),
('LY', '+218', 'Libya', 'Various', TRUE),
('MG', '+261', 'Madagascar', 'Various', TRUE),
('MW', '+265', 'Malawi', 'Various', TRUE),
('ML', '+223', 'Mali', 'Various', TRUE),
('MR', '+222', 'Mauritania', 'Various', TRUE),
('MU', '+230', 'Mauritius', 'Various', TRUE),
('MA', '+212', 'Morocco', 'Various', TRUE),
('MZ', '+258', 'Mozambique', 'Various', TRUE),
('NA', '+264', 'Namibia', 'Various', TRUE),
('NE', '+227', 'Niger', 'Various', TRUE),
('NG', '+234', 'Nigeria', 'Various', TRUE),
('RW', '+250', 'Rwanda', 'Various', TRUE),
('ST', '+239', 'São Tomé and Príncipe', 'Various', TRUE),
('SN', '+221', 'Senegal', 'Various', TRUE),
('SC', '+248', 'Seychelles', 'Various', TRUE),
('SL', '+232', 'Sierra Leone', 'Various', TRUE),
('SO', '+252', 'Somalia', 'Various', TRUE),
('ZA', '+27', 'South Africa', 'Various', TRUE),
('SS', '+211', 'South Sudan', 'Various', TRUE),
('SD', '+249', 'Sudan', 'Various', TRUE),
('SZ', '+268', 'Eswatini', 'Various', TRUE),
('TZ', '+255', 'Tanzania', 'Various', TRUE),
('TG', '+228', 'Togo', 'Various', TRUE),
('TN', '+216', 'Tunisia', 'Various', TRUE),
('UG', '+256', 'Uganda', 'Various', TRUE),
('ZM', '+260', 'Zambia', 'Various', TRUE),
('ZW', '+263', 'Zimbabwe', 'Various', TRUE),

-- OCEANIA
('AU', '+61', 'Australia', 'Various', TRUE),
('FJ', '+679', 'Fiji', 'Various', TRUE),
('KI', '+686', 'Kiribati', 'Various', TRUE),
('MH', '+692', 'Marshall Islands', 'Various', TRUE),
('FM', '+691', 'Micronesia', 'Various', TRUE),
('NR', '+674', 'Nauru', 'Various', TRUE),
('NZ', '+64', 'New Zealand', 'Various', TRUE),
('PW', '+680', 'Palau', 'Various', TRUE),
('PG', '+675', 'Papua New Guinea', 'Various', TRUE),
('WS', '+685', 'Samoa', 'Various', TRUE),
('SB', '+677', 'Solomon Islands', 'Various', TRUE),
('TO', '+676', 'Tonga', 'Various', TRUE),
('TV', '+688', 'Tuvalu', 'Various', TRUE),
('VU', '+678', 'Vanuatu', 'Various', TRUE),

-- TERRITORIES & SPECIAL REGIONS
('AX', '+358', 'Åland Islands', 'Various', TRUE),
('AS', '+1684', 'American Samoa', 'Various', TRUE),
('AW', '+297', 'Aruba', 'Various', TRUE),
('BM', '+1441', 'Bermuda', 'Various', TRUE),
('BQ', '+599', 'Caribbean Netherlands', 'Various', TRUE),
('KY', '+1345', 'Cayman Islands', 'Various', TRUE),
('CX', '+61', 'Christmas Island', 'Various', TRUE),
('CC', '+61', 'Cocos Islands', 'Various', TRUE),
('CK', '+682', 'Cook Islands', 'Various', TRUE),
('CW', '+599', 'Curaçao', 'Various', TRUE),
('FK', '+500', 'Falkland Islands', 'Various', TRUE),
('FO', '+298', 'Faroe Islands', 'Various', TRUE),
('GF', '+594', 'French Guiana', 'Various', TRUE),
('PF', '+689', 'French Polynesia', 'Various', TRUE),
('GI', '+350', 'Gibraltar', 'Various', TRUE),
('GL', '+299', 'Greenland', 'Various', TRUE),
('GP', '+590', 'Guadeloupe', 'Various', TRUE),
('GU', '+1671', 'Guam', 'Various', TRUE),
('GG', '+44', 'Guernsey', 'Various', TRUE),
('IM', '+44', 'Isle of Man', 'Various', TRUE),
('JE', '+44', 'Jersey', 'Various', TRUE),
('MQ', '+596', 'Martinique', 'Various', TRUE),
('YT', '+262', 'Mayotte', 'Various', TRUE),
('MS', '+1664', 'Montserrat', 'Various', TRUE),
('NC', '+687', 'New Caledonia', 'Various', TRUE),
('NU', '+683', 'Niue', 'Various', TRUE),
('NF', '+672', 'Norfolk Island', 'Various', TRUE),
('MP', '+1670', 'Northern Mariana Islands', 'Various', TRUE),
('PR', '+1787', 'Puerto Rico', 'Various', TRUE),
('RE', '+262', 'Réunion', 'Various', TRUE),
('BL', '+590', 'Saint Barthélemy', 'Various', TRUE),
('SH', '+290', 'Saint Helena', 'Various', TRUE),
('MF', '+590', 'Saint Martin', 'Various', TRUE),
('PM', '+508', 'Saint Pierre and Miquelon', 'Various', TRUE),
('SX', '+1721', 'Sint Maarten', 'Various', TRUE),
('GS', '+500', 'South Georgia', 'Various', TRUE),
('SJ', '+47', 'Svalbard and Jan Mayen', 'Various', TRUE),
('TK', '+690', 'Tokelau', 'Various', TRUE),
('TC', '+1649', 'Turks and Caicos Islands', 'Various', TRUE),
('VI', '+1340', 'US Virgin Islands', 'Various', TRUE),
('WF', '+681', 'Wallis and Futuna', 'Various', TRUE),
('EH', '+212', 'Western Sahara', 'Various', TRUE)

ON CONFLICT (prefix, country_code) DO NOTHING;
